### ISSUE TITLE
Set http header SOAPAction automatically in soap 1.1 

### ISSUE THREAD

**Issue by nobre84** [bulldog2011/nano#5]
Hi! I'm consuming a 1.1 soap service that requires the SOAPAction http header. I had to manually insert it in the generated class even when it is explicity set in the wsdl.
PS: Pico is able to insert this header automatically in objective-c

Thanks for the fine framework !

**Comment by bulldog2011** [comment]
Hi,

You can set http header on Pico client at runtime.

You can find details in this sample/tutorial:
http://bulldog2011.github.io/blog/2013/03/29/pico-tutorial-3-hello-ebay-finding/
in step 3, create a shared client.

Thx!
-William

**Comment by bulldog2011** [comment]
Hi,

I just remembered/found that SOAPAction http header is automatically added in the generated XXXService_SOAPClient in every method. I just confused why you need to manually add it again.

Can you confirm.

Thx!
-William

**Comment by nobre84** [comment]
Hi, with the following WSDL: http://wsrobos.novaprolink.com.br/v2/WSConsultaProcessos.WSConsultaProcesso.svc?wsdl
The SOAPClient class did not add the SOAPAction header automatically - I managed to add it myself like in the ebay sample, I'm just curious because for the same wsdl it was added by pico for objective-c.

**Comment by bulldog2011** [comment]
Hi,

I'll add SOAP action header in nano codegen, will post here to let you know when it's done.

Thx!
-William

**Comment by bulldog2011** [comment]
SOAP action header has been added in mwsc for nano, if possible, please re-download the zip to verify.

Thx!
-William

**Comment by nobre84** [comment]
Verified and working fine now with latest mwsc!
