### ISSUE TITLE
JAXBElement<String>

### ISSUE THREAD

**Issue by marckaraujo** [bulldog2011/nano#9]
I generated the wsdl: http://www.semhora.com/Payment.wsdl with mwsc.
And all elements come with this JAXBElement<String>, but it isnt supported in Android.

What I need to do?

Thanks

**Comment by bulldog2011** [comment]
Hi,

Looks like the same issue in pico, please try mwsc custom binding to resolve,
https://github.com/bulldog2011/pico/issues/2

Thx!
-William

**Comment by marckaraujo** [comment]
Thanks! Now it works.

One more question, my wsdl needs to be authenticated with name and password, but I can't find the way to do it.
Could you help me? I will be very thankfully with your help.

**Comment by bulldog2011** [comment]
Hi,

What do you mean by "my wsdl needs to be authenticated with name and password"?

Thx!
-William

**Comment by marckaraujo** [comment]
I solved, I just used:

soap.getAsyncHttpClient().setBasicAuth("username", "password");

Thanks!! you made a really good job.
